# -*- coding: utf-8 -*-
"""DV_DA_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W2jyB31FKbf41E0z-D_pRKTXRUWCkKfr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/DoctorVisits - DA.csv")
df.head()

df.info()

df["illness"].value_counts()

df["gender"].value_counts()

y=list(df.income)
plt.boxplot(y)
plt.show()

df.groupby(["gender","reduced"]).mean()

sns.heatmap(df.isnull(),cbar=False,cmap="viridis")

plt.figure(figsize=(10,10))
sns.heatmap(df.corr(),cbar=True,annot=True,cmap='Blues')

plt.figure(figsize=(10,10))
plt.scatter(x='income',y='visits',data=df)
plt.xlabel('income')
plt.ylabel('visits')

sns.histplot(df.gender,bins=2)

label=["yes","no"]
Y=df[df['freepoor']=="yes"]
N=df[df['freepoor']=='no']
x=[Y.shape[0],N.shape[0]]
plt.figure(figsize=(5,5))
plt.pie(x,labels=label)
plt.title("% of people getting govt health Insurence due to low income ")
plt.show()

Y=df[df['private']=='yes']
N=df[df['private']=='no']
x=[Y.shape[0],N.shape[0]]
plt.figure(figsize=(5,5))
plt.pie(x,labels=label)
plt.title('% of people have private health Insurence ')
plt.show()

Y=df[df['freerepat']=='yes']
N=df[df['freerepat']=='no']
x=[Y.shape[0],N.shape[0]]
plt.figure(figsize=(5,5))
plt.pie(x,labels=label)
plt.title("% of people getting govt health Insurence due to old age , disability or veteran status")
plt.show()

df=df.groupby('gender')['reduced'].sum().to_frame().reset_index()
plt.barh(df['gender'],df['reduced'],color=['cornflowerblue','lightseagreen'])
plt.title('Bar Chart')
plt.ylabel('gender')
plt.xlabel('reduced activity')
plt.show()